export const posts = [
  {
    id: 1,
    name: 'Ansh Kyal',
    title: 'Journey from ICSE to JEE: Overcoming Challenges',
    userType: 'MENTOR',
    type: 'UNIVERSITY',
    creData: 'IIT Indore',
    thumbnail: 'https://static.wematchnow.com/common/mentor_column/mock/column/Ansh_Kyal/user_thumbnail.jpg',
    mainImage: 'https://static.wematchnow.com/common/mentor_column/dev/thumbnail_image_list/Ansh_Kyal_pc.png',
  },
  {
    id: 2,
    name: 'Rajendra Kumar',
    title: 'Defying the Odds: My JEE Journey',
    userType: 'MENTOR',
    type: 'UNIVERSITY',
    creData: 'IIT Gandhinagar',
    thumbnail: 'https://static.wematchnow.com/common/mentor_column/mock/column/Rajendra_Kumar/user_thumbnail.jpg',
    mainImage: 'https://static.wematchnow.com/common/mentor_column/dev/thumbnail_image_list/Rajendra_Kumar_pc.png',
  },
  {
    id: 3,
    name: 'Yash Gehlot',
    title: 'From Average to IIT',
    userType: 'MENTOR',
    type: 'UNIVERSITY',
    creData: 'IIT Roorkee',
    thumbnail: 'https://static.wematchnow.com/common/mentor_column/mock/column/Yash_Gehlot/user_thumbnail.jpg',
    mainImage: 'https://static.wematchnow.com/common/mentor_column/dev/thumbnail_image_list/Yash_Gehlot_pc.png',
  },
  {
    id: 4,
    name: 'Gaurav Kumar',
    title: 'JEE journey: persistence, adaptation',
    userType: 'MENTOR',
    type: 'UNIVERSITY',
    creData: 'IIT BHU',
    thumbnail: 'https://static.wematchnow.com/common/mentor_column/mock/column/Gaurav_Kumar/user_thumbnail.jpg',
    mainImage: 'https://static.wematchnow.com/common/mentor_column/dev/thumbnail_image_list/Gaurav_Kumar_pc.png',
  },
  {
    id: 5,
    name: 'Aditya Kumar Rawani',
    title: 'IIT journey: resilience, success',
    userType: 'MENTOR',
    type: 'UNIVERSITY',
    creData: 'IIT Guwahati',
    thumbnail: 'https://static.wematchnow.com/common/mentor_column/mock/column/Aditya_Kumar/user_thumbnail.jpg',
    mainImage: 'https://static.wematchnow.com/common/mentor_column/dev/thumbnail_image_list/Aditya_Kumar_Rawani_pc.png',
  },
];