import type {Metadata} from "next";

export const metadata: Metadata = {
  title: {
    template: '멘토컬럼 | %s',
    default: "멘토컬럼",
  },
  description: "Generated by create next app",
};

export default function Layout({children}: Readonly<{ children: React.ReactNode; }>) {
  return (
      <>

        {children}
      </>
  );
}